# These are supported funding model platforms

github: Michael-A-Kuykendall
ko_fi: mikekuykendall
open_collective: rustchain
buy_me_a_coffee: michaelakuykendall
custom: ["mailto:michaelallenkuykendall@gmail.com"]
